name: youtubeapi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  freezed_annotation:
  json_annotation:
  intl:
  dio:
  flutter_riverpod:
  flutter_dotenv:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Rampart_One
      fonts:
        - asset: assets/fonts/Rampart_One/RampartOne-Regular.ttf
          weight: 400
